In [1]:
import numpy as np

In [2]:
# Q1. Create a rank 1 array with elements 1,2,3 
a = np.array([1,2,3])

In [3]:
# Q2. print its type and shape
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a.shape)

(3,)


In [5]:
# Q3. Print each of its element individually 
print("Elements of given array: ");  
for i in range(0, len(a)):  
    print(a[i]),   

Elements of given array: 
1
2
3


In [6]:
# Q4. Change element of the array at zero index with 5
a[0] = ("5")

In [7]:
print(a)

[5 2 3]


In [8]:
# Create a rank 2 array like [[1,2,3],[4,5,6]] 
b = np.array([[1,2,3],[4,5,6]])  

In [9]:
# Q6. print its shape
print(b.shape)

(2, 3)


In [10]:
print(b[0, 0], b[0, 1], b[1, 0]) 

1 2 4


Numpy also provides many functions to create arrays:

In [11]:
# Q1. Create an array of all zeros with shape (2,2) 
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [12]:
# Q2. Create an array of all ones with shape (1,2) 
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [13]:
# Q3. Create a constant array with shape (2,2) and value 7 
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [14]:
# Q4. Create a 2x2 identity matrix 
d = np.eye(2)  
print(d)

[[1. 0.]
 [0. 1.]]


In [15]:
# Q5. Create an (2,2) array filled with random values
e = np.random.random((2,2))
print(e)

[[0.78445676 0.14996626]
 [0.71058442 0.45412205]]


# 2. Array indexing
Numpy offers several ways to index into arrays.

a) Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [16]:
import numpy as np

In [17]:
# Q1. Create the following rank 2 array with shape (3, 4) and values as given below
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
# Q2. Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2): 
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [19]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

In [20]:
# Q1. Create the following rank 2 array with shape (3, 4) value as given below
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [21]:
# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the original array:

# Q2. Create Rank 1 view of the second row of a (1 marks)
row_r1 = a[1, :]    # Rank 1 view of the second row of a

# Q3. # Create Rank 2 view of the second row of a 
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a

print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [22]:
# Q4. Create Rank 1 view of the second column of a 
# Start code here
col_r1 = a[:, 1] 

# Q5. Create Rank 2 view of the second column of a 
# Start code here
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape) 
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**b) Integer array indexing:** When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [23]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# Using the array "a" created above and integer indexing

# Q1. print an array  that should have shape (3,) and should print "[1 4 5]" when printed
## Start code
print(a[[0, 1, 2], [0, 1, 0]]) 

# The method of integer array indexing that you implemented is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:

# Q2. Print the array that prints "[2 2]" when printed
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [24]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a) 


# Create an array of indices
b = np.array([0, 2, 0, 1])

# Q1. Select one element from each row of a using the indices in b and print it (1 marks)
## Start code
print(a[np.arange(4), b])

# Q2. Mutate one element from each row of a using the indices in b by adding 10 to it and print it (1 marks)
## Start code
a[np.arange(4), b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


**c) Boolean array indexing:** Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [26]:
a = np.array([[1,2], [3, 4], [5, 6]])

# Q1. Find the elements of a that are bigger than 2 using boolean indexing 
## Start code
bool_idx = (a > 2)

print(bool_idx)     

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  

# We can do all of the above in a single concise statement:
print(a[a > 2])    

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation from the given link.
http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

# 3. Datatypes
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [27]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int32
float64
int64


You can read all about numpy datatypes in the documentation from the given link.
http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html

# 4. Array math
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [28]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Q1. print Elementwise sum of x and y 
print(x + y)
print(np.add(x, y))

# Q2. print Elementwise difference of x and y
print(x - y)
print(np.subtract(x, y))

# Q3. print Elementwise product of x and y
print(x * y)
print(np.multiply(x, y))

# Q4. print Elementwise divison of x and y 
print(x / y)
print(np.divide(x, y))

# Q5. print Elementwise square root of x 
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, * is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [29]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Q1. print Inner product of vectors v and w; 
print(v.dot(w))
print(np.dot(v, w))

# Q2. print Matrix / vector product of x and v; 
print(x.dot(v))
print(np.dot(x, v))

# Q3. print Matrix / matrix product of x and y;
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum:

In [30]:
x = np.array([[1,2],[3,4]])

# Q1. Compute sum of all elements and print it
print(np.sum(x)) 

# Q2. Compute sum of each column and print it 
print(np.sum(x, axis=0))

# Q3. Compute sum of each row and print it 
print(np.sum(x, axis=1))

10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the documentation on the provided link.
http://docs.scipy.org/doc/numpy/reference/routines.math.html

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [31]:
x = np.array([[1,2], [3,4]])

# Q1. print x and its transpose 
print(x)    
print(x.T) 

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])

# Q2. print v and its transpose 
print(v)
print(v.T)  

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


Numpy provides many more functions for manipulating arrays; you can see the full list in the documentation on the provided link.
http://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html

## 5. Broadcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [32]:
# You will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Q1. Add the vector v to each row of the matrix x with an explicit loop and store in y 
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix *x* is very large, computing an explicit loop in Python could be slow. Note that adding the vector *v* to each row of the matrix *x* is equivalent to forming a matrix *vv* by stacking multiple copies of v vertically, then performing elementwise summation of *x* and *vv*. We could implement this approach like this:

In [33]:
# You will add the vector v to each row of the matrix x,
# storing the result in the matrix y

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

# Q1. Stack 4 copies of v on top of each other using tile method and store it in vv. 
## Start code here
vv = np.tile(v, (4, 1))
print(vv)                 

# Q2. Add x and vv elementwise 
## Start code here
y = x + vv
print(y)  

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [34]:
# You will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

# Q1. Add v to each row of x using broadcasting (2 marks)
## Start code here
y = x + v
print(y) 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line y = x + v works even though x has shape (4, 3) and v has shape (3,) due to broadcasting; this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

> If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.

>The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.

>The arrays can be broadcast together if they are compatible in all dimensions.

>After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.

>In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension.

>If this explanation does not make sense, try reading the explanation from the documentation or this explanation.http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc

>Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the documentation from the link provided.
http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs

Here are some applications of broadcasting:

In [35]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

# Q1. Compute an outer product of v and w and print it (hint:we first reshape v to be a column)
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])

# Q2. Add v to ecah row of x and print it 
print(x + v)

# Add a vector to each column of a matrix
# Q3. Add vector w to each column of x and print it 
print((x.T + w).T)

# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

## 6. Numpy Documentation
This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the numpy reference to find out much more about numpy.
http://docs.scipy.org/doc/numpy/reference/

# 7. Conclusion

NumPy is a Linear Algebra Library for python.

It is the core library for scientific computation in python.

It is super fast as it has bindings to C libraries.

It provides a high-performance multidimensional array object and tools for working with arrays.